name: Echo Message and Slack Notifications

on:
  push:
    branches:
      - main

jobs:
  echo-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Echo a Message
        run: echo "Hello from GitHub Actions!"

      - name: Send a Slack Notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: always
          text: 'GitHub Action: A message was echoed.'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
