name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Echo a Message
        run: echo "Hello from GitHub Actions!"

      - name: Send a Slack Notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          text: 'GitHub Action: A message was echoed.'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
